const professionalsData = [
  {
    id: 1,
    name: "Mary's Plumbing",
    tags: "RESIDENTIAL • COMMERCIAL",
    description:
      "Expert plumbing services for residential and commercial systems...",
    rating: "4.5",
    rate: "FCFA 42,500",
    image: "../images/pictures/female-plumber.jpg",
  },
  {
    id: 2,
    name: "Mike's Electric",
    tags: "RESIDENTIAL • EMERGENCY",
    description:
      "Licensed electrician providing 24/7 support for outages, panel upgrades...",
    rating: "4.7",
    rate: "FCFA 47,500",
    image: "../images/pictures/solar.jpg",
  },
  {
    id: 3,
    name: "Elite HVAC Services",
    tags: "HEATING COOLING ELECTRICAL REPAIRS",
    description:
      "Reliable heating and cooling solutions, AC diagnostics, and installation...",
    rating: "4.8",
    rate: "FCFA 55,000",
    image: "../images/pictures/electrician2.jpg",
  },
  {
    id: 4,
    name: "Dave's Handyman",
    tags: "GENERAL REPAIRS",
    description:
      "Your go-to professional for general home repairs, painting and odd jobs...",
    rating: "4.6",
    rate: "FCFA 37,500",
    image: "../images/pictures/worker.jpg",
  },

  {
    id: 5,
    name: "Alpha Carpentry",
    tags: "WOODWORK",
    description: "Custom cabinets...",
    rating: "3.8",
    rate: "FCFA 45,000",
    image: "../images/pictures/apliance.jpg",
  },
  {
    id: 6,
    name: "Pro Capentry",
    tags: "Capentry",
    description: "Quality woodwork services...",
    rating: "3.6",
    rate: "32,500",
    image: "../images/pictures/story-img.jpg",
  },
  {
    id: 7,
    name: "Apex Cleaning",
    tags: "CLEANING",
    description: "House maintenance...",
    rating: "4.0",
    rate: "FCFA 35,000",
    image: "../images/pictures/general.jpg",
  },
  {
    id: 8,
    name: "Smart Fix Appliance",
    tags: "APPLIANCE",
    description: "Washers and dryers...",
    rating: "3.9",
    rate: "FCFA 50,000",
    image: "../images/pictures/technician.jpg",
  },

  {
    id: 9,
    name: "Licensed Electrical",
    tags: "ELECTRICAL",
    description: "Skilled electricians for...",
    rating: "4.5",
    rate: "FCFA 25,000",
    image: "../images/pictures/electrical.jpg",
  },
  {
    id: 10,
    name: "Bolt Roofing",
    tags: "ROOFING",
    description: "Shingle restoration...",
    rating: "4.8",
    rate: "FCFA 60,000",
    image: "../images/pictures/roofing.jpg",
  },
  {
    id: 11,
    name: "Custom Capentry",
    tags: "Carpentry",
    description: "Quality woodwork, framing...",
    rating: "3.5",
    rate: "FCFA 47,500",
    image: "../images/pictures/carpenter.jpg",
  },
  {
    id: 12,
    name: "Expert Plumbing",
    tags: "PLUMBING",
    description: "Vetted professionals for..",
    rating: "3.9",
    rate: "FCFA 35,000",
    image: "../images/pictures/blue-pipe.jpg",
  },
];
